import type { Product } from "./types"

export const products: Product[] = [
  {
    id: "1",
    name: "Bolo de Ninho com Morango",
    description: "Camadas de massa macia com creme de leite ninho e morangos frescos.",
    image: "/elegant-layered-cake-with-strawberries-and-cream--.jpg",
    basePrice: 89.9,
    status: "sob-encomenda",
    category: "bolos-festivos",
    weights: [
      { label: "1kg", priceModifier: 0 },
      { label: "1.5kg", priceModifier: 35 },
      { label: "2kg", priceModifier: 70 },
    ],
    flavors: ["Baunilha", "Chocolate"],
    additionals: [
      { name: "Topper Personalizado", price: 25 },
      { name: "Velas Personalizadas", price: 15 },
      { name: "Plaquinha de Chocolate", price: 12 },
    ],
  },
  {
    id: "2",
    name: "Bolo Red Velvet",
    description: "O clássico bolo vermelho com cobertura de cream cheese.",
    image: "/red-velvet-cake-with-cream-cheese-frosting--elegan.jpg",
    basePrice: 95.9,
    status: "sob-encomenda",
    category: "bolos-festivos",
    weights: [
      { label: "1kg", priceModifier: 0 },
      { label: "1.5kg", priceModifier: 40 },
      { label: "2kg", priceModifier: 80 },
    ],
    flavors: ["Red Velvet"],
    additionals: [
      { name: "Topper Personalizado", price: 25 },
      { name: "Velas Personalizadas", price: 15 },
      { name: "Flores Comestíveis", price: 20 },
    ],
  },
  {
    id: "3",
    name: "Bolo Espatulado de Chocolate",
    description: "Bolo artesanal com textura rústica e recheio cremoso de brigadeiro gourmet.",
    image: "/rustic-chocolate-spatula-cake-with-brigadeiro-fill.jpg",
    basePrice: 79.9,
    status: "pronta-entrega",
    category: "bolos-festivos",
    weights: [
      { label: "1kg", priceModifier: 0 },
      { label: "1.5kg", priceModifier: 30 },
      { label: "2kg", priceModifier: 60 },
    ],
    flavors: ["Chocolate", "Chocolate Branco"],
    additionals: [
      { name: "Topper Personalizado", price: 25 },
      { name: "Morangos Extras", price: 18 },
    ],
  },
  {
    id: "4",
    name: "Bolo no Pote - Brigadeiro",
    description: "Camadas de bolo, brigadeiro gourmet e granulado belga.",
    image: "/brazilian-brigadeiro-cake-in-a-jar--layered-desser.jpg",
    basePrice: 18.9,
    status: "pronta-entrega",
    category: "bolos-no-pote",
    weights: [
      { label: "200g", priceModifier: 0 },
      { label: "300g", priceModifier: 8 },
    ],
    flavors: ["Brigadeiro", "Brigadeiro Branco"],
    additionals: [{ name: "Colher Decorada", price: 3 }],
  },
  {
    id: "5",
    name: "Bolo no Pote - Ninho com Nutella",
    description: "Combinação irresistível de creme de leite ninho com Nutella.",
    image: "/cake-in-jar-with-cream-and-nutella-layers--elegant.jpg",
    basePrice: 22.9,
    status: "pronta-entrega",
    category: "bolos-no-pote",
    weights: [
      { label: "200g", priceModifier: 0 },
      { label: "300g", priceModifier: 10 },
    ],
    flavors: ["Baunilha"],
    additionals: [
      { name: "Colher Decorada", price: 3 },
      { name: "Nutella Extra", price: 5 },
    ],
  },
  {
    id: "6",
    name: "Brigadeiro Gourmet (25 un)",
    description: "Brigadeiros artesanais com chocolate belga.",
    image: "/gourmet-brazilian-brigadeiros-on-elegant-display--.jpg",
    basePrice: 45.0,
    status: "pronta-entrega",
    category: "docinhos",
    weights: [
      { label: "25 unidades", priceModifier: 0 },
      { label: "50 unidades", priceModifier: 40 },
      { label: "100 unidades", priceModifier: 85 },
    ],
    flavors: ["Tradicional", "Ninho", "Maracujá", "Pistache"],
    additionals: [
      { name: "Embalagem Premium", price: 15 },
      { name: "Mix de Sabores", price: 10 },
    ],
  },
  {
    id: "7",
    name: "Beijinho (25 un)",
    description: "Docinhos de coco delicados com acabamento artesanal.",
    image: "/brazilian-beijinho-coconut-sweets-on-elegant-tray-.jpg",
    basePrice: 42.0,
    status: "sob-encomenda",
    category: "docinhos",
    weights: [
      { label: "25 unidades", priceModifier: 0 },
      { label: "50 unidades", priceModifier: 38 },
      { label: "100 unidades", priceModifier: 80 },
    ],
    flavors: ["Tradicional", "Com Nutella"],
    additionals: [{ name: "Embalagem Premium", price: 15 }],
  },
  {
    id: "8",
    name: "Mini Coxinha (50 un)",
    description: "Coxinhas artesanais com recheio cremoso de frango.",
    image: "/brazilian-coxinha-appetizers-on-elegant-serving-pl.jpg",
    basePrice: 65.0,
    status: "sob-encomenda",
    category: "salgados",
    weights: [
      { label: "50 unidades", priceModifier: 0 },
      { label: "100 unidades", priceModifier: 55 },
    ],
    flavors: ["Frango", "Frango com Catupiry"],
    additionals: [{ name: "Molho Especial", price: 8 }],
  },
  {
    id: "9",
    name: "Mini Esfiha (50 un)",
    description: "Esfihas abertas com carne temperada artesanalmente.",
    image: "/mini-brazilian-esfiha-meat-pastries-on-wooden-boar.jpg",
    basePrice: 60.0,
    status: "sob-encomenda",
    category: "salgados",
    weights: [
      { label: "50 unidades", priceModifier: 0 },
      { label: "100 unidades", priceModifier: 50 },
    ],
    flavors: ["Carne", "Queijo"],
    additionals: [{ name: "Mix de Sabores", price: 5 }],
  },
]
